#!/usr/bin/python3

from src.Common import Profile

with Profile("import"):
    import pathlib
    import argparse
    import fnmatch
    import pickle

    from src.Common import Profile, Print, dotdict
    from src.InstructionBlockDescription import InstructionBlockDescription
    from src.SequenceTransformer import SequenceTransformer
    from src.TimingsAnalyzer import TimingsAnalyzer

def main():

    # helper function to filter out unneeded variants
    def filter_variants(model, pattern, verbose=True):
        invert = pattern.startswith("-")
        if invert:
            pattern = pattern[1:]
        variants = model.variants
        model.variants = [var for var in model.variants if fnmatch.fnmatch(var.name, pattern) != invert]
        if not verbose:
            return (var for var in variants if var not in model.variants)
        for var in (var for var in variants if var not in model.variants):
            print(f"  > WARNING: filtered out variant '{var.name}'")
        for var in model.variants:
            print(f"  > using variant '{var.name}'")

    def valid_path(path):
        return pathlib.Path(path).resolve()

    # path to output folder
    output_dirname = pathlib.Path(__file__).resolve().parent / "out"

    ############################# parse arguments #############################
    parser = argparse.ArgumentParser()
    # input models
    parser.add_argument("schedule_model"     , help="Path to the schedule model pickle file.")
    parser.add_argument("struct_model"       , nargs='?', help="Path to the structure model pickle file. Required for delay analysis.")
    # options
    parser.add_argument("-v", "--verbose"    , action="store_true", help="Enables verbose output.")
    parser.add_argument("-p", "--print"      , action="store_true", help="Prints the resulting timings for each basic block and each variant.")
    parser.add_argument("-P", "--print-bb"   , action="store_true", help="Prints the basic blocks used.")
    parser.add_argument("-n", "--num"        , nargs= 1, type=int, required=False, default=None, help="Only analyses the first `n` variants.")
    parser.add_argument("-d", "--default-dynamic-delay", nargs=1, type=int, default=[None], help="Sets a default value for all dynamic delays.", metavar="DELAY")
    parser.add_argument("--rank"             , action="store_true", help="Prints the rank/group of each predicted CPI.")    
    parser.add_argument("--cores"            , type=str, help="Filters out any variant that does not match the given Wildcard pattern.", metavar="WILDCARD")
    parser.add_argument("--export"           , nargs= 1, type=valid_path, default=[None], help="Exports the results to the given path.", metavar="EXPORT_DIR")
    parser.add_argument("--export-suffix"    , nargs= 1, type=str, default=[None], help="Optional suffix for result filenames.")
    # input basic blocks
    parser.add_argument("--examples"         , nargs='?', type=str, const='*', help="Loads example basic blocks. A Wildcard pattern can be used to load only certain examples.", metavar="WILDCARD")
    parser.add_argument("--files"            , nargs='+', type=valid_path, const=None, help="Parses code blocks from disk. Multiple input files can be specified.")
    # targets
    parser.add_argument("--sequence-analysis", action="store_true", help="Evaluates the timing model sequentially for each instruction in a basic blocks to determine the CPI.")
    parser.add_argument("--symbolic-analysis", nargs= 1, type=str, default=[""],
                                               help="Comma separated list of keywords, which are used to match scheudling nodes whose delay should be made symbolic. " + \
                                                    "Initiates symbolic sequenced timing analysis.", metavar="OP1,OP2,OP3")
    parser.add_argument("--cpi"              , action="store_true", help="Predicts the CPI for each instruction block. Prints to stdout.")
    parser.add_argument("--xisaac"           , action="store_true", help="Extract delays for the symbolic variables from the variants directly (Only works with XISAAC variants generated by GenIE).")
    # other targes
    parser.add_argument("--block-schedule"   , action="store_true", help="Generates scheduling functions for each code block.")
    parser.add_argument("--schedule-graph"   , action="store_true", help="Generates scheduling functions graphs for the generated block scheduling functions.")

    args = parser.parse_args()

    ############################# initializations #############################
    
    # if isinstance(args.out_dir, list):
    #     [args.out_dir] = args.out_dir

    print("-- INITIALIZING --")
    print(" > Arguments:\n  >" + ",\n  > ".join(f"'{f}': {args.__getattribute__(f)}" for f in vars(args)))

    # transform arguments
    [args.default_dynamic_delay] = args.default_dynamic_delay
    [args.export_suffix]  = args.export_suffix
    [args.export]         = args.export

    symbolic_names = list(filter(lambda arg: len(arg) > 0, (arg.strip() for arg in args.symbolic_analysis[0].split(","))))
    args.symbolic_analysis = len(symbolic_names)

    # find CorePerfDSL models
    schedule_model = struct_model = None
    model_path = pathlib.Path(args.schedule_model).resolve()
    if model_path.is_dir():
        print(" > Attemping to load default models...")
        if args.struct_model:
            parser.error(f"Loading default models would ignore '--struct-model' argument, aborting!")
        args.schedule_model = model_path / "schedule.model"
        args.struct_model   = model_path / "frontend.model"
    elif not model_path.is_file():
        parser.error(f"Invalid path to schedule model!")
    elif not args.schedule_model.endswith(".model"):
        parser.error(f"Expected model file to end with '.model'!")

    if args.schedule_graph and not args.block_schedule:
        args.block_schedule = True

    if sum(bool(arg) for arg in (args.files, args.examples)) > 1:
        parser.error(f"Conflicting arguments: either use --files or --examples!")
    if sum(bool(arg) for arg in (args.sequence_analysis, args.symbolic_analysis, args.block_schedule)) > 1:
        parser.error(f"Conflicting arguments: either use --sequence-analysis, --symbolic-names, or --block-schedule!")

    if args.cpi and not symbolic_names:
        args.sequence_analysis = True

    ############################ load pickle files ############################
    with open(args.schedule_model, 'rb') as file:
        print(" > loading schedule model...")
        with Profile("  > unpickling schedule model"):
            schedule_model = pickle.load(file)

    if args.struct_model:
        with open(args.struct_model, 'rb') as file:
            print(" > loading structural model...")
            with Profile("  > unpickling struct model"):
                struct_model = pickle.load(file)
    elif args.cpi:
        parser.error(f"Missing structural model for CPI analysis!")

    # only load first n models
    if args.num is not None:
        [args.num] = args.num
        assert args.num > 0
        schedule_model.variants = schedule_model.variants[:args.num]
        struct_model.variants   = struct_model.variants[:args.num]

    ################################## setup ##################################
    symbolic_delay_vectors = {}
    if args.symbolic_analysis:
        # extract symbolic delays from variants
        if args.xisaac:
            for variant in struct_model.getAllVariants():
                pipeline = variant.getPipeline()
                mirco_ops = pipeline.getAllMicroactions()
                resources = (res for op in mirco_ops for res in op.getResources())
                resources = (res for res in resources for var in symbolic_names if var in res.name)
                # NOTE: hardcoded V0 variant here, may use any other variant
                symbolic_delay_vectors[variant.name] = { f"V0{r.name[r.name.index('_'):]}": r.delay for r in resources }
        # generate sample symbolic delays from variants
        else:
            variant  = struct_model.getAllVariants()[0]
            pipeline = variant.getPipeline()
            mirco_ops = pipeline.getAllMicroactions()
            resources = (res for op in mirco_ops for res in op.getResources())
            resources = list(res for res in resources for var in symbolic_names if var in res.name)
            for delay in [1, 2, 3]:
                symbolic_delay_vectors[f"{variant.name}_d{delay}"] = { r.name: delay for r in resources }

    # filter out variants
    if args.cores:
        print(" > filtering variants...")
        filter_variants(schedule_model, args.cores)
        if struct_model is not None:
            filter_variants(struct_model, args.cores, verbose=False)

    if args.symbolic_analysis:
        schedule_model.variants = [schedule_model.variants[0]]
        struct_model.variants   = [struct_model.variants[0]]

    if len(schedule_model.variants) == 0:
        print(" > ERROR: No variants available!")
        exit(1)


    ############################ load basic blocks ############################
    code_blocks = []

    # load code blocks from file(s)
    if args.files:
        with Print.indent_scope(3):
            with Profile("  > loading basic blocks"):
                code_blocks = InstructionBlockDescription.load_from_files(args.files, verbose=args.verbose)
    # load example code blocks
    elif args.examples:
        import tests.TestVectors as Examples # lazy import
        code_blocks = Examples.test_vectors(pattern=args.examples)

    if len(code_blocks) == 0:
        print(" > ERROR: No code blocks to generate schedule models! Use `--examples` or `--files` to load code blocks!")
        exit(1)


    ###################### block scheduling functions #########################
    # NOTE: This was the initial approach of creating a "block scheduling function". 
    #       I left it in, but it can no longer be used for the analysis, only for visualisations
    if args.block_schedule:
        from src.BlockSchedulingTransformer import BlockSchedulingTransformer # lazy import

        block_schedule = BlockSchedulingTransformer(verbose=args.verbose,
                                                    rename_edges=args.schedule_graph) \
            .transform(schedule_model, code_blocks)

        # render block schedules
        if args.schedule_graph:
            from backends.schedule_viewer.SchedulingModelViewer import SchedulingModelViewer # lazy import

            outdir = args.export
            if not isinstance(args.export, pathlib.Path):
                outdir = pathlib.Path(output_dirname).resolve()

            SchedulingModelViewer() \
                .execute(block_schedule, outdir, alternate_color=True, show_delays=True)

    ############################ delay analysis ###############################
    # exit early
    if not args.sequence_analysis and not args.symbolic_analysis:
        print(" > WARNING: nothing to do! Use `--cpi`, `--sequence-analysis`, or `--symbolic-analysis`!")
        exit(0)

    sequence_model = SequenceTransformer(verbose=args.verbose,
                                         symbolic_vars=symbolic_names,
                                         default_dynamic_delay=args.default_dynamic_delay,
                                         accumulate_timings=args.print) \
        .analyze_all_variants(schedule_model, code_blocks)

    # exit early
    if not args.cpi:
        exit(0)

    results = None
    # sequence timing analysis
    if args.sequence_analysis:
        results = TimingsAnalyzer(print_history=args.print,
                                  print_code_blocks=args.print_bb,
                                  accumulate_stalls=args.print) \
            .estimate_cpi(sequence_model, schedule_model, struct_model)

    # symbolic timing analysis
    elif args.symbolic_analysis:
        results = TimingsAnalyzer(print_history=args.print,
                                  print_code_blocks=args.print_bb,
                                  accumulate_stalls=False # not supported yet
                                  ) \
            .solve_symbolic_delay_for_cpi(sequence_model, schedule_model, struct_model, symbolic_delay_vectors)

    ############################ post processing #############################
    # exit early
    if not results:
        exit(0)

    # export results
    if isinstance(args.export, pathlib.Path):
        import json # lazy import

        for variant_name in results:
            blocks = results[variant_name]
            args.export.mkdir(parents=True, exist_ok=True)
            with open(args.export / f"{variant_name}_{args.export_suffix + "_" if args.export_suffix else ""}results.json", "w") as f:
                f.write(json.dumps(blocks, indent=4))

    # print total CPI if possible
    final_results = {}
    for variant_name in results:
        blocks       = results[variant_name]
        total_weight = sum(bb.weight for bb in blocks.values() if bb.weight is not None)
        if total_weight == 0:
            print("ERROR: Cannot determine total CPI, missing weights for basic blocks!")
            exit(0)

        final_results[variant_name] = dotdict({
            "total_cpi": sum((bb.cpi * bb.weight / total_weight) for bb in blocks.values()),
            "total_weight": total_weight
        })

    if final_results:
        # NOTE: rounding cpi to avoid generating multiple ranks for slight variations in CPI due to weighting
        max_digits = 10
        ranks = { value: (idx + 1) for idx, value in enumerate(sorted(set(round(result.total_cpi, max_digits) for result in final_results.values()))) } \
            if args.rank else None

        print()
        for variant_name, result in final_results.items():
            print(f"Variant: {variant_name:>15},\t",
                f"total CPI: {result.total_cpi:.6f},\t",
                f"total weight: {result.total_weight * 100:.5f}%",
                f"\trank: {ranks[round(result.total_cpi, max_digits)]}" if ranks else "")

if __name__ == "__main__":
    with Profile("main"):
        main()