[BoolConfigurations]
arch.enable_semihosting=true
simple_mem_system.error_on_invalid_access=true
jit.verify=false
jit.debug=false
etiss.load_integrated_libraries=true
simple_mem_system.print_dbus_access=false
simple_mem_system.print_to_file=false
etiss.exit_on_loop=false
etiss.log_pc=false
etiss.enable_dmi=false
[StringConfigurations]
arch.cpu=XIsaacCore
etiss.output_path_prefix=
jit.type=TCCJIT
#vp.elf_file=
[IntConfigurations]
simple_mem_system.memseg_origin_00=16777216
simple_mem_system.memseg_length_00=8388608
simple_mem_system.memseg_origin_01=25165824
simple_mem_system.memseg_length_01=67108864
arch.cpu_cycle_time_ps=31250
etiss.loglevel=4
[Plugin PerformanceEstimatorPlugin]
#plugin.perfEst.uArch=
plugin.perfEst.printDir=.
